export type Product = {
  id: number;
  name: string;
  brand: string;
  price: number;
  mrp: number;
  rating: number;
  reviews: number;
  image: string;
  badge?: string;
  badgeColor?: string;
  category: 'deals' | 'electronics' | 'fashion';
  freeDelivery: boolean;
};

export const products: Product[] = [
  {
    id: 1,
    name: 'boAt Rockerz 450 Bluetooth Headphone',
    brand: 'boAt',
    price: 1299,
    mrp: 3990,
    rating: 4.3,
    reviews: 84210,
    image: 'https://picsum.photos/seed/boat-rockerz-450/300/300',
    badge: '67% off',
    badgeColor: 'bg-green-100 text-green-700',
    category: 'deals',
    freeDelivery: true,
  },
  {
    id: 2,
    name: 'Samsung 108cm (43") 4K Ultra HD Smart LED TV',
    brand: 'Samsung',
    price: 28990,
    mrp: 55900,
    rating: 4.5,
    reviews: 32100,
    image: 'https://picsum.photos/seed/samsung-4k-tv-43/300/300',
    badge: '48% off',
    badgeColor: 'bg-green-100 text-green-700',
    category: 'deals',
    freeDelivery: true,
  },
  {
    id: 3,
    name: 'Realme Narzo N55 (Prime Blue, 4GB RAM, 64GB)',
    brand: 'Realme',
    price: 8999,
    mrp: 12999,
    rating: 4.2,
    reviews: 15320,
    image: 'https://picsum.photos/seed/realme-narzo-n55/300/300',
    badge: '30% off',
    badgeColor: 'bg-green-100 text-green-700',
    category: 'deals',
    freeDelivery: true,
  },
  {
    id: 4,
    name: 'Prestige Iris 750W Mixer Grinder (3 Jars)',
    brand: 'Prestige',
    price: 1699,
    mrp: 4295,
    rating: 4.1,
    reviews: 9875,
    image: 'https://picsum.photos/seed/prestige-mixer-grinder/300/300',
    badge: '60% off',
    badgeColor: 'bg-green-100 text-green-700',
    category: 'deals',
    freeDelivery: false,
  },
  {
    id: 5,
    name: 'Apple iPhone 15 (Black, 128GB)',
    brand: 'Apple',
    price: 69999,
    mrp: 79900,
    rating: 4.7,
    reviews: 122400,
    image: 'https://picsum.photos/seed/apple-iphone-15-black/300/300',
    badge: 'Best Seller',
    badgeColor: 'bg-accent/10 text-accent',
    category: 'electronics',
    freeDelivery: true,
  },
  {
    id: 6,
    name: 'Dell Inspiron 15 Intel Core i5 Laptop (8GB, 512GB SSD)',
    brand: 'Dell',
    price: 47990,
    mrp: 62990,
    rating: 4.4,
    reviews: 8230,
    image: 'https://picsum.photos/seed/dell-inspiron-15-laptop/300/300',
    badge: '24% off',
    badgeColor: 'bg-green-100 text-green-700',
    category: 'electronics',
    freeDelivery: true,
  },
  {
    id: 7,
    name: 'Sony WH-1000XM5 Wireless Noise-Cancelling Headphones',
    brand: 'Sony',
    price: 24990,
    mrp: 34990,
    rating: 4.6,
    reviews: 41560,
    image: 'https://picsum.photos/seed/sony-wh1000xm5/300/300',
    badge: '28% off',
    badgeColor: 'bg-green-100 text-green-700',
    category: 'electronics',
    freeDelivery: true,
  },
  {
    id: 8,
    name: 'Canon EOS 1500D 24.1MP DSLR Camera (EF-S 18-55mm)',
    brand: 'Canon',
    price: 30995,
    mrp: 44995,
    rating: 4.5,
    reviews: 18900,
    image: 'https://picsum.photos/seed/canon-eos-1500d/300/300',
    badge: '31% off',
    badgeColor: 'bg-green-100 text-green-700',
    category: 'electronics',
    freeDelivery: true,
  },
  {
    id: 9,
    name: 'Roadster Men Slim Fit Casual Shirt',
    brand: 'Roadster',
    price: 479,
    mrp: 1199,
    rating: 4.0,
    reviews: 5430,
    image: 'https://picsum.photos/seed/roadster-men-shirt/300/300',
    badge: '60% off',
    badgeColor: 'bg-green-100 text-green-700',
    category: 'fashion',
    freeDelivery: false,
  },
  {
    id: 10,
    name: 'Biba Women Ethnic Kurta Set (S–XXL)',
    brand: 'Biba',
    price: 1399,
    mrp: 2799,
    rating: 4.3,
    reviews: 7210,
    image: 'https://picsum.photos/seed/biba-women-kurta-set/300/300',
    badge: '50% off',
    badgeColor: 'bg-green-100 text-green-700',
    category: 'fashion',
    freeDelivery: false,
  },
  {
    id: 11,
    name: 'Puma Running Shoes (Black, UK 9)',
    brand: 'Puma',
    price: 1999,
    mrp: 4999,
    rating: 4.2,
    reviews: 22110,
    image: 'https://picsum.photos/seed/puma-running-shoes-black/300/300',
    badge: '60% off',
    badgeColor: 'bg-green-100 text-green-700',
    category: 'fashion',
    freeDelivery: true,
  },
  {
    id: 12,
    name: 'Ray-Ban Wayfarer RB2132 Sunglasses',
    brand: 'Ray-Ban',
    price: 5999,
    mrp: 9500,
    rating: 4.6,
    reviews: 3980,
    image: 'https://picsum.photos/seed/rayban-wayfarer-rb2132/300/300',
    badge: '36% off',
    badgeColor: 'bg-green-100 text-green-700',
    category: 'fashion',
    freeDelivery: true,
  },
];
